spring:
  application:
    name: portfolio
  
  profiles:
    active: local  # default profile is local/development

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver

  # MVC Configuration for proper error handling
  mvc:
    problemdetails:
      enabled: true

# General Information about Application
app:
  name: Portfolio Backend API
  version: 1.0.0
  description: Backend APIs for Personal Portfolio Website

# Server Configuration (default is localhost at port 8080)
server:
  url: http://localhost:8080

# CORS Configuration (overridden by profile-specific configs)
cors:
  allowed-origins: http://localhost:5173

# Swagger Configuration for API Testing using UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

# Resilience4j Rate Limiter Configuration  (Default provided by spring framework)
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 100  # Number of requests allowed
        limit-refresh-period: 1m  # Time window
        timeout-duration: 0s  # Time thread waits for permission (0 = immediate)
      admin:
        limit-for-period: 50
        limit-refresh-period: 1m
        timeout-duration: 0s
      public:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 0s
